:PROPERTIES:
:ID:       dfa334b9-6522-480f-8dbf-bbb71de5758d
:END:
#+title: AI

* 概念联系
人工智能（Artificial Intelligence）的目标是造出具有“人类智能”的程序，是最宏大的一个概念，其目的是制造出可以通过“图灵测试”的程序，并没有规定这个程序是如何制造的。

机器学习（Machine Learning）是制造 AI 的一个子任务。它是训练计算机程序或系统在没有明确指令的情况下执行任务的科学，也就是让 AI 具有“学习能力”，我个人觉得就是将一部分逻辑让渡给程序本身，形成一个“黑箱”。需要强调的是，AI 不应该只具有学习能力，它还应该具有自然语言处理、计算机视觉、分析推理、情感、机器人（也就是在物理世界中运动和感知）等能力，这些能力可以不通过机器学习的方式来实现，也就是“白箱实现”。此外还需要强调，学习能力与其他能力并非完全正交，其他能力也可以使用机器学习“黑箱”，比如 chatgpt 就是一个用机器学习方法来实现自然语言处理的例子。

可以说“黑箱”是机器学习的核心特征。但是需要说明，“黑箱”并不意味着完全不可解释，比如说对于机器学习中的最小二乘法，我们知道参数的设定是为了让数据预测的方差达到最小，并不是完全不能理解参数的设定。只是我们没办法在编写程序的时候就明确地写出具体的参数，参数的获得需要通过机器本身的学习而不是程序员的学习。有点像“数学”和“统计”的区别。

深度学习（Deep Learning）是机器学习中的一种技术，它的核心特点是使用人工神经网络这种仿生学思想进行机器学习。实现机器学习还可以有其他方法，比如支持向量机，最小二乘法，主成分分析，感知机等。因为采用了人工神经网络，导致深度学习与其他机器学习方法（也称作“传统机器学习方法”）有许多不同：

- 数据依赖程度：传统机器学习适合数据量较小的任务，深度学习适合处理大数据。
- 硬件依赖程度：深度学习十分依赖于硬件设施，因为计算量实在太大。它会涉及很多矩阵运算，因此很多深度学习都要求有GPU 参与运算。
- 特征工程：在训练一个机器学习模型的时候，需要首先确定学习哪些特征，比如识别人脸可能并不需要身高特征。在传统机器学习方法中，几乎所有特征都需要人为确认后，再进行手工特征编码。而深度学习试图自己从数据中自动学习特征。
- 解决问题的方式：传统机器学习通常先把问题分成几块，一个个地解决好之后，再重新组合。深度学习是一次性地解决好问题。
- 训练和推理运行时间：传统机器学习的训练时间快而推理时间慢，深度学习的训练时间慢而推理时间快。

大型语言模型 (Large Language Model, LLM) 是深度学习的一种模型，它强调两点，一个是规模极大（本来深度学习就是机器学习中规模较大的一种了），另一个是用于自然语言处理。它的核心技术是 transformer 模型，这个模型采用了注意力（attention）机制，这种模型使得原本只能有 10 多层的人工神经网络模型拓展到了几百几千层，进而推动了整体模型的规模，使得其训练效果好到出圈。

正如机器学习可以助力 AI 在其他方面的功能，LLM 也可以助力深度学习在其他方面的不足。这种助力是极其豪横的。也就是说，一个极其强大的自然语言处理模型（LLM），看上去只要继续发展，就可以解决全部的 AI 问题。

* 语义空间
我们都知道人工神经网络中每一层的神经网络都可以对前一层输入进行一次矩阵运算（如果刨除激活不算的话），从线性代数的知识可知，这其实是在做一次空间映射，如果矩阵是 ~M x N~ 的，那么每经过一层，就是将一个原本在 ~M~ 维空间向量映射到一个 ~N~ 维的空间中。

人工神经网络的原理是将一段数据先 tokenize ，也就是将原本的字符串之类（比如我们和 chatgpt 说的话）的东西转换成一组一维的标量，每个标量被称为一个 token ，然后将他们映射到一个向量空间中，这个过程叫做“嵌入”（embedding），然后就是对于这个向量的一次次映射。

那么我们这样做的直观理解是什么，我觉得是这样的，人工神经网络是在描述语义。说白了，就是通过构建一个语义空间的方式去掌握各个 token 的语义，语义空间就是一个多维向量空间。那么为什么一个多维向量空间就可以描述语义呢？因为多维向量空间中存在距离，我们可以用距离的方式来描述两个 token 的相似性，而这就构成了语义。比如在一个空间中，当我们观测到“苹果，梨，香蕉”的距离很近，那么可能就是因为她们都具有水果的语义。

语义空间的设计有两个极端，一个是一维标量，另一个是独热码。如果用一维标量的话，有些复杂的语义没有办法表示，比如说“苹果”，它既有“水果”的意思，又有“电子品牌”的意思，那么它应该既和“香蕉”离得近，又和“三星”离得近，但是“香蕉”和“三星”不应该离那么近。而独热码则是尽可能的扩大自己的维度，并只使用一个维度，那么我们很难表示出相近的含义，因为独热码的所有点的距离都是相同的。
